# Generated by Django 5.0.6 on 2024-05-30 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='is_enabled',
            new_name='is_active',
        ),
    ]
